# see: http://about.travis-ci.org/docs/user/languages/php/
# example: https://github.com/travis-ci-examples/php/blob/master/.travis.yml

language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=mysql
#  - DB=pgsql

# optionally set up exclutions and allowed failures in the matrix
#matrix:
#  exclude:
#    - php: hhvm
#      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
#  allow_failures:
#    - php: 7.0
#    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - composer self-update
    - composer install

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
#script: phpunit --configuration phpunit_$DB.xml --coverage-text

# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#yourfavouriteroomfortravis"
